---
# tasks file for goagent
- name: Download gocd agent
  get_url:
    url: https://download.gocd.org/gocd.repo
    dest: /etc/yum.repos.d/gocd.repo
- name: install the latest version of gocd
  yum:
    name: go-agent
    state: latest
- name: start gocd agent
  service:
    name: go-agent
    state: started